services:
  webserver:
    image: brightwebb11/webserver:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
     - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    image: brightwebb11/instalog-api:latest
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: instalog
      DB_USERNAME: instalog
      DB_PASSWORD: Webilor1994@..
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Webilor1994@..
      MYSQL_DATABASE: instalog
      MYSQL_USER: instalog
      MYSQL_PASSWORD: Webilor1994@..
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: instalog
      PMA_PASSWORD: Webilor1994@..
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: